#######################################
#                                     #
#         Koko_KeywordBlocker         #
#         Author:Koko_red7214         #
#                                     #
#######################################

#Whether to enable the blocking function
enable: true

#If player send the keyword then send this msg to the player
#ColorCode " : "
blockmessage: '&cThe word is blocked, cannot be sent!'

# %player% = Player Name
# %msg% = Blocked Message
# %location% = Player Location
adminmessage: '&c%player% has send a blocked msg : &c%msg%!'

#All the following keywords will be blocked
keyword:
  - 'fuck'
  - 'fck'