#######################################
#                                     #
#         Koko_KeywordBlocker         #
#         Author:Koko_red7214         #
#                                     #
#######################################

#Whether to enable the blocking function
enable: true

#If player send the keyword then send this msg to the player
#ColorCode " & "
blockmessage: '&cThe word is blocked, cannot be sent!'

# %player% = Player Name
# %location% = Player Location
adminmessage: '&5%player% &chas send a blocked msg!'

#All the following keywords will be blocked
keyword:
  - 'fuck'
  - 'fck'